[package]
name = "dht-next"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[features]
test-support = []
diagnostics = []

[dependencies]
routing-types = { path = "../routing-types" }
crypto = { path = "../crypto" }
wire = { path = "../wire" }
blake3 = "1"
snow = "0.10"
zeroize = "1.9"

[dev-dependencies]
swarm = { path = "../swarm" }
proptest.workspace = true

